Commands (reworked:tm:)!
ValkyrienSkies/vs-core pull request #43
Opened 2022-12-01 17:03 UTC by ewoudje

2022-12-01 19:29 UTC, Rubydesic requested changes

2022-12-01 19:29 UTC, Rubydesic commented on api-game/src/main/kotlin/org/valkyrienskies/core/game/VSCoreCommands.kt
> +object VSCoreCommands {
This should be an interface

2022-12-01 19:29 UTC, Rubydesic commented on api/src/main/kotlin/org/valkyrienskies/core/api/ships/Ship.kt
> +    val slug: String // Unique string identifier for the ship
Make this nullable. Maybe it should be an attachment?

2022-12-01 19:29 UTC, Rubydesic commented on api-game/src/main/kotlin/org/valkyrienskies/core/game/VSCoreCommands.kt
> +    fun renameShip(ship: ServerShip, newName: String) {
Needs to return some kind of feedback interface in case it failed (same for the rest)

2022-12-01 19:29 UTC, Rubydesic commented on api/src/main/kotlin/org/valkyrienskies/core/api/ships/Ship.kt
> +    val slug: String // Unique string identifier for the ship
Also is there any better name than slug?

2022-12-01 19:29 UTC, Rubydesic commented on api/src/main/kotlin/org/valkyrienskies/core/api/world/ServerShipWorld.kt
> +    fun deleteShip(ship: ServerShip)
Put this in API game for now

2022-12-01 19:30 UTC, ewoudje commented on api-game/src/main/kotlin/org/valkyrienskies/core/game/VSCoreCommands.kt
> +    fun renameShip(ship: ServerShip, newName: String) {
I wrap the calls around a try catch

2022-12-07 11:01 UTC, ewoudje commented
scaleShip and teleportShip are TODO waiting for the synced modifications thingies

2023-01-09 23:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/ValkyrienSkies/vs-core?pullRequest=43) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/ValkyrienSkies/vs-core?pullRequest=43) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/ValkyrienSkies/vs-core?pullRequest=43) it.</sub>

2023-07-20 18:27 UTC, ewoudje commented
Commands have been merged in another PR

2023-07-20 18:27 UTC, closed without merging